// lib/smc/bank/batch2.ts
// Questions 181–360: Multiplication · Division · Money

import type { BankQuestion } from './types';

export const BATCH2: BankQuestion[] = [

// ── MULTIPLICATION (Q181–250) ──────────────────────────────────────────────

{ id:'b2-181', stem:'3 × 7 = ?', type:'open', answer:'21', solution:'3 groups of 7 = 21.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-182', stem:'4 × 6 = ?', type:'open', answer:'24', solution:'4 groups of 6 = 24.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-183', stem:'5 × 8 = ?', type:'open', answer:'40', solution:'5 groups of 8 = 40.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-184', stem:'6 × 9 = ?', type:'open', answer:'54', solution:'6 groups of 9 = 54.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-185', stem:'7 × 7 = ?', type:'open', answer:'49', solution:'7 groups of 7 = 49.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-186', stem:'8 × 6 = ?', type:'open', answer:'48', solution:'8 groups of 6 = 48.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-187', stem:'9 × 4 = ?', type:'open', answer:'36', solution:'9 groups of 4 = 36.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-188', stem:'2 × 9 = ?', type:'open', answer:'18', solution:'2 groups of 9 = 18.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-189', stem:'A box holds 8 oranges. How many oranges are in 6 boxes?', type:'open', answer:'48', unit:'oranges', solution:'6 × 8 = 48.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-190', stem:'A car has 4 wheels. How many wheels do 9 cars have?', type:'open', answer:'36', unit:'wheels', solution:'9 × 4 = 36.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-191', stem:'5 children each have 7 crayons. How many crayons are there in total?', type:'open', answer:'35', unit:'crayons', solution:'5 × 7 = 35.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-192', stem:'A flower has 6 petals. How many petals do 8 flowers have?', type:'open', answer:'48', unit:'petals', solution:'8 × 6 = 48.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-193', stem:'There are 7 days in a week. How many days are there in 4 weeks?', type:'open', answer:'28', unit:'days', solution:'4 × 7 = 28.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-194', stem:'A spider has 8 legs. How many legs do 5 spiders have?', type:'open', answer:'40', unit:'legs', solution:'5 × 8 = 40.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-195', stem:'What is 3 × 3 × 3?', type:'open', answer:'27', solution:'3×3=9. 9×3=27.', topic:'multiplication', diff:2, h:'Model Drawing' },
{ id:'b2-196', stem:'A teacher gives 9 stickers to each of her 6 students. How many stickers does she give out?', type:'open', answer:'54', unit:'stickers', solution:'6 × 9 = 54.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-197', stem:'There are 10 eggs in a carton. How many eggs are in 8 cartons?', type:'open', answer:'80', unit:'eggs', solution:'8 × 10 = 80.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-198', stem:'Each table has 5 chairs. How many chairs are needed for 9 tables?', type:'open', answer:'45', unit:'chairs', solution:'9 × 5 = 45.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-199', stem:'What is the product of 8 and 7?', type:'open', answer:'56', solution:'8 × 7 = 56.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-200', stem:'? × 6 = 42', type:'open', answer:'7', solution:'42 ÷ 6 = 7.', topic:'multiplication', diff:2, h:'Work Backwards' },
{ id:'b2-201', stem:'4 × ? = 36', type:'open', answer:'9', solution:'36 ÷ 4 = 9.', topic:'multiplication', diff:2, h:'Work Backwards' },
{ id:'b2-202', stem:'? × 8 = 64', type:'open', answer:'8', solution:'64 ÷ 8 = 8.', topic:'multiplication', diff:2, h:'Work Backwards' },
{ id:'b2-203', stem:'A packet has 6 biscuits. Min bought 7 packets. She ate 8 biscuits. How many are left?', type:'open', answer:'34', unit:'biscuits', solution:'7×6=42. 42−8=34.', topic:'multiplication', diff:2, h:'Model Drawing' },
{ id:'b2-204', stem:'Sam scores 9 points per basket and scores 6 baskets. Ben scores 7 points per basket and scores 8 baskets. Who scores more and by how many?', type:'open', answer:'Ben by 2', solution:'Sam: 9×6=54. Ben: 7×8=56. Ben wins by 56−54=2 points.', topic:'multiplication', diff:3, h:'Model Drawing' },
{ id:'b2-205', stem:'There are 4 rows of seats with 8 seats in each row. How many seats are there?', type:'open', answer:'32', unit:'seats', solution:'4 × 8 = 32.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-206', stem:'A bookshelf has 5 shelves with 9 books on each. How many books are there?', type:'open', answer:'45', unit:'books', solution:'5 × 9 = 45.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-207', stem:'A snail travels 3 cm every hour. How far does it travel in 9 hours?', type:'open', answer:'27', unit:'cm', solution:'9 × 3 = 27.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-208', stem:'2 bags of marbles have 9 marbles each. 3 bags have 7 marbles each. How many marbles altogether?', type:'open', answer:'39', unit:'marbles', solution:'2×9=18. 3×7=21. 18+21=39.', topic:'multiplication', diff:2, h:'Model Drawing' },
{ id:'b2-209', stem:'What is 10 × 10?', type:'open', answer:'100', solution:'10 × 10 = 100.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-210', stem:'A farmer plants 8 rows of corn with 9 seeds in each row. How many seeds does he plant?', type:'open', answer:'72', unit:'seeds', solution:'8 × 9 = 72.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-211', stem:'Each hen lays 2 eggs per day. How many eggs do 7 hens lay in 3 days?', type:'open', answer:'42', unit:'eggs', solution:'7×2=14 eggs per day. 14×3=42 eggs in 3 days.', topic:'multiplication', diff:2, h:'Model Drawing' },
{ id:'b2-212', stem:'What is 6 × 6?', type:'open', answer:'36', solution:'6 × 6 = 36.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-213', stem:'A toy shop sells 7 kites a day. How many kites does it sell in a week (7 days)?', type:'open', answer:'49', unit:'kites', solution:'7 × 7 = 49.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-214', stem:'Three friends each buy 8 balloons. How many balloons do they have altogether?', type:'open', answer:'24', unit:'balloons', solution:'3 × 8 = 24.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-215', stem:'A number multiplied by 5 gives 45. What is the number?', type:'open', answer:'9', solution:'45 ÷ 5 = 9.', topic:'multiplication', diff:2, h:'Work Backwards' },
{ id:'b2-216', stem:'A number multiplied by 7 gives 63. What is the number?', type:'open', answer:'9', solution:'63 ÷ 7 = 9.', topic:'multiplication', diff:2, h:'Work Backwards' },
{ id:'b2-217', stem:'Each page of a book has 8 pictures. How many pictures are on 7 pages?', type:'open', answer:'56', unit:'pictures', solution:'7 × 8 = 56.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-218', stem:'In a game, each correct answer scores 9 points. Ann gets 6 answers right and Bob gets 8 right. How many more points does Bob score than Ann?', type:'open', answer:'18', unit:'points', solution:'Bob: 8×9=72. Ann: 6×9=54. Difference: 72−54=18.', topic:'multiplication', diff:2, h:'Model Drawing' },
{ id:'b2-219', stem:'What is 4 × 4 × 2?', type:'open', answer:'32', solution:'4×4=16. 16×2=32.', topic:'multiplication', diff:2, h:'Model Drawing' },
{ id:'b2-220', stem:'How many legs do 9 dogs have?', type:'open', answer:'36', unit:'legs', solution:'9 × 4 = 36.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-221', stem:'A sticker book has 10 pages with 8 stickers on each page. How many stickers in the book?', type:'open', answer:'80', unit:'stickers', solution:'10 × 8 = 80.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-222', stem:'5 × 6 + 5 × 4 = ?', type:'open', answer:'50', solution:'5×6=30. 5×4=20. 30+20=50.', topic:'multiplication', diff:2, h:'Simplify the Problem' },
{ id:'b2-223', stem:'A number multiplied by itself gives 64. What is the number?', type:'open', answer:'8', solution:'8 × 8 = 64.', topic:'multiplication', diff:2, h:'Guess and Check' },
{ id:'b2-224', stem:'A number multiplied by itself gives 81. What is the number?', type:'open', answer:'9', solution:'9 × 9 = 81.', topic:'multiplication', diff:2, h:'Guess and Check' },
{ id:'b2-225', stem:'How many hours are there in 4 days?', type:'open', answer:'96', unit:'hours', solution:'1 day=24 hours. 4×24=96.', topic:'multiplication', diff:2, h:'Model Drawing' },
{ id:'b2-226', stem:'A packet of sweets has 6 sweets. How many sweets are in 9 packets?', type:'open', answer:'54', unit:'sweets', solution:'9 × 6 = 54.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-227', stem:'There are 5 fingers on each hand. How many fingers on 8 hands?', type:'open', answer:'40', unit:'fingers', solution:'8 × 5 = 40.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-228', stem:'A box has 3 layers. Each layer has 4 rows of 3 cans. How many cans altogether?', type:'open', answer:'36', unit:'cans', solution:'4×3=12 cans per layer. 12×3=36 cans total.', topic:'multiplication', diff:3, h:'Model Drawing' },
{ id:'b2-229', stem:'Two numbers have a product of 36. Their sum is 13. What are the numbers?', type:'open', answer:'4 and 9', solution:'4×9=36, 4+9=13. ✓', topic:'multiplication', diff:3, h:'Guess and Check' },
{ id:'b2-230', stem:'Two numbers have a product of 48. Their sum is 14. What are the numbers?', type:'open', answer:'6 and 8', solution:'6×8=48, 6+8=14. ✓', topic:'multiplication', diff:3, h:'Guess and Check' },
{ id:'b2-231', stem:'A multiplication table shows 7 × 6 = ?', type:'open', answer:'42', solution:'7 × 6 = 42.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-232', stem:'A bag of sweets weighs 5g. How much do 9 bags weigh?', type:'open', answer:'45', unit:'g', solution:'9 × 5 = 45.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-233', stem:'How many minutes are there in 3 hours?', type:'open', answer:'180', unit:'minutes', solution:'1 hour=60 minutes. 3×60=180.', topic:'multiplication', diff:2, h:'Model Drawing' },
{ id:'b2-234', stem:'Raja has 4 boxes with 9 crayons each and 3 boxes with 6 crayons each. How many crayons does he have?', type:'open', answer:'54', unit:'crayons', solution:'4×9=36. 3×6=18. 36+18=54.', topic:'multiplication', diff:2, h:'Model Drawing' },
{ id:'b2-235', stem:'If 1 orange costs $2, how much do 8 oranges cost?', type:'open', answer:'16', unit:'$', solution:'8 × $2 = $16.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-236', stem:'A sandwich uses 2 slices of bread. How many slices are needed for 9 sandwiches?', type:'open', answer:'18', unit:'slices', solution:'9 × 2 = 18.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-237', stem:'Multiply the tens digit and ones digit of 69. What do you get?', type:'open', answer:'54', solution:'6 × 9 = 54.', topic:'multiplication', diff:2, h:'Restate the Problem' },
{ id:'b2-238', stem:'What is 3 × 8 + 4 × 5?', type:'open', answer:'44', solution:'3×8=24. 4×5=20. 24+20=44.', topic:'multiplication', diff:2, h:'Model Drawing' },
{ id:'b2-239', stem:'How many cents are in $7?', type:'open', answer:'700', unit:'cents', solution:'1 dollar=100 cents. 7×100=700.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-240', stem:'Which is greater: 9 × 8 or 7 × 10? By how much?', type:'open', answer:'9×8 by 2', solution:'9×8=72. 7×10=70. 72>70 by 2.', topic:'multiplication', diff:2, h:'Logical Reasoning' },
{ id:'b2-241', stem:'A container holds 6 litres. How many litres in 8 containers?', type:'open', answer:'48', unit:'litres', solution:'8 × 6 = 48.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-242', stem:'3 pencils cost $9. How much do 9 pencils cost?', type:'open', answer:'27', unit:'$', solution:'1 pencil costs $9÷3=$3. 9 pencils: 9×$3=$27.', topic:'multiplication', diff:2, h:'Simplify the Problem' },
{ id:'b2-243', stem:'Each child plants 5 seeds. There are 7 children. How many seeds are planted?', type:'open', answer:'35', unit:'seeds', solution:'7 × 5 = 35.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-244', stem:'A pack of 9 balloons costs $9. How much do 5 packs cost?', type:'open', answer:'45', unit:'$', solution:'5 × $9 = $45.', topic:'multiplication', diff:2, h:'Model Drawing' },
{ id:'b2-245', stem:'Two numbers multiply to give 56. One number is 7. What is the other?', type:'open', answer:'8', solution:'56 ÷ 7 = 8.', topic:'multiplication', diff:2, h:'Work Backwards' },
{ id:'b2-246', stem:'What is the missing factor? 9 × ? = 72', type:'open', answer:'8', solution:'72 ÷ 9 = 8.', topic:'multiplication', diff:2, h:'Work Backwards' },
{ id:'b2-247', stem:'How many toes do 7 people have? (each person has 10 toes)', type:'open', answer:'70', unit:'toes', solution:'7 × 10 = 70.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-248', stem:'A parking lot has 6 rows with 8 cars in each row. How many cars are parked?', type:'open', answer:'48', unit:'cars', solution:'6 × 8 = 48.', topic:'multiplication', diff:1, h:'Model Drawing' },
{ id:'b2-249', stem:'What is the value of 4 × 9 − 6 × 5?', type:'open', answer:'6', solution:'4×9=36. 6×5=30. 36−30=6.', topic:'multiplication', diff:2, h:'Simplify the Problem' },
{ id:'b2-250', stem:'Mia earns $8 a day. How much does she earn in 6 days?', type:'open', answer:'48', unit:'$', solution:'6 × $8 = $48.', topic:'multiplication', diff:1, h:'Model Drawing' },

// ── DIVISION (Q251–310) ──────────────────────────────────────────────────

{ id:'b2-251', stem:'28 ÷ 4 = ?', type:'open', answer:'7', solution:'28 ÷ 4 = 7.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-252', stem:'36 ÷ 6 = ?', type:'open', answer:'6', solution:'36 ÷ 6 = 6.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-253', stem:'45 ÷ 9 = ?', type:'open', answer:'5', solution:'45 ÷ 9 = 5.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-254', stem:'63 ÷ 7 = ?', type:'open', answer:'9', solution:'63 ÷ 7 = 9.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-255', stem:'56 ÷ 8 = ?', type:'open', answer:'7', solution:'56 ÷ 8 = 7.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-256', stem:'24 ÷ 3 = ?', type:'open', answer:'8', solution:'24 ÷ 3 = 8.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-257', stem:'40 ÷ 5 = ?', type:'open', answer:'8', solution:'40 ÷ 5 = 8.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-258', stem:'72 ÷ 8 = ?', type:'open', answer:'9', solution:'72 ÷ 8 = 9.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-259', stem:'30 cookies are shared equally among 6 children. How many does each child get?', type:'open', answer:'5', unit:'cookies', solution:'30 ÷ 6 = 5.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-260', stem:'48 sweets are packed equally into 8 bags. How many sweets in each bag?', type:'open', answer:'6', unit:'sweets', solution:'48 ÷ 8 = 6.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-261', stem:'35 seeds are planted equally in 7 pots. How many seeds per pot?', type:'open', answer:'5', unit:'seeds', solution:'35 ÷ 7 = 5.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-262', stem:'54 pupils are divided into groups of 9. How many groups are there?', type:'open', answer:'6', unit:'groups', solution:'54 ÷ 9 = 6.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-263', stem:'A rope of 72 cm is cut into pieces of 9 cm each. How many pieces are there?', type:'open', answer:'8', unit:'pieces', solution:'72 ÷ 9 = 8.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-264', stem:'There are 42 pencils. Each student gets 6. How many students receive pencils?', type:'open', answer:'7', unit:'students', solution:'42 ÷ 6 = 7.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-265', stem:'81 ÷ 9 = ?', type:'open', answer:'9', solution:'81 ÷ 9 = 9.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-266', stem:'A farmer collects 64 eggs. He puts them in boxes of 8. How many boxes does he need?', type:'open', answer:'8', unit:'boxes', solution:'64 ÷ 8 = 8.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-267', stem:'$28 is shared equally among 4 children. How much does each child get?', type:'open', answer:'7', unit:'$', solution:'28 ÷ 4 = 7.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-268', stem:'60 flowers are arranged in bunches of 5. How many bunches are there?', type:'open', answer:'12', unit:'bunches', solution:'60 ÷ 5 = 12.', topic:'division', diff:2, h:'Model Drawing' },
{ id:'b2-269', stem:'100 pupils march in rows of 10. How many rows are there?', type:'open', answer:'10', unit:'rows', solution:'100 ÷ 10 = 10.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-270', stem:'How many groups of 6 can be made from 90?', type:'open', answer:'15', unit:'groups', solution:'90 ÷ 6 = 15.', topic:'division', diff:2, h:'Model Drawing' },
{ id:'b2-271', stem:'A bag of 80 sweets is shared among 8 friends equally. Each friend gives half of their sweets to their parent. How many sweets does each parent receive?', type:'open', answer:'5', unit:'sweets', solution:'80÷8=10 per friend. Half: 10÷2=5.', topic:'division', diff:2, h:'Model Drawing' },
{ id:'b2-272', stem:'48 children sit at tables of 8. How many tables are needed?', type:'open', answer:'6', unit:'tables', solution:'48 ÷ 8 = 6.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-273', stem:'A number divided by 7 gives 8. What is the number?', type:'open', answer:'56', solution:'7 × 8 = 56.', topic:'division', diff:2, h:'Work Backwards' },
{ id:'b2-274', stem:'A number divided by 9 gives 6. What is the number?', type:'open', answer:'54', solution:'9 × 6 = 54.', topic:'division', diff:2, h:'Work Backwards' },
{ id:'b2-275', stem:'45 apples are put into bags of 9. How many bags are needed?', type:'open', answer:'5', unit:'bags', solution:'45 ÷ 9 = 5.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-276', stem:'There are 6 shelves with equal numbers of books. There are 54 books in total. How many books are on each shelf?', type:'open', answer:'9', unit:'books', solution:'54 ÷ 6 = 9.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-277', stem:'Share 70 marbles equally among 10 children. How many does each get?', type:'open', answer:'7', unit:'marbles', solution:'70 ÷ 10 = 7.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-278', stem:'A shopkeeper packs 56 toys equally into 7 boxes. How many toys in each box?', type:'open', answer:'8', unit:'toys', solution:'56 ÷ 7 = 8.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-279', stem:'What number divided by 8 gives 7?', type:'open', answer:'56', solution:'7 × 8 = 56.', topic:'division', diff:2, h:'Work Backwards' },
{ id:'b2-280', stem:'18 children are put into equal groups. Each group has 3 children. How many groups are there?', type:'open', answer:'6', unit:'groups', solution:'18 ÷ 3 = 6.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-281', stem:'A ribbon of 63 cm is cut into 9 equal pieces. How long is each piece?', type:'open', answer:'7', unit:'cm', solution:'63 ÷ 9 = 7.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-282', stem:'40 children play in teams of 8. How many teams are there?', type:'open', answer:'5', unit:'teams', solution:'40 ÷ 8 = 5.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-283', stem:'A cook uses 3 eggs to make 1 cake. How many cakes can she make with 27 eggs?', type:'open', answer:'9', unit:'cakes', solution:'27 ÷ 3 = 9.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-284', stem:'30 ÷ ? = 5', type:'open', answer:'6', solution:'30 ÷ 5 = 6, so the missing number is 6.', topic:'division', diff:2, h:'Work Backwards' },
{ id:'b2-285', stem:'? ÷ 4 = 9', type:'open', answer:'36', solution:'4 × 9 = 36.', topic:'division', diff:2, h:'Work Backwards' },
{ id:'b2-286', stem:'? ÷ 7 = 6', type:'open', answer:'42', solution:'7 × 6 = 42.', topic:'division', diff:2, h:'Work Backwards' },
{ id:'b2-287', stem:'72 flowers are divided equally into 8 vases. 5 flowers from one vase are removed. How many flowers are in that vase now?', type:'open', answer:'4', unit:'flowers', solution:'72÷8=9 per vase. 9−5=4.', topic:'division', diff:2, h:'Model Drawing' },
{ id:'b2-288', stem:'A teacher has 90 stickers. She gives 9 to each child. How many children receive stickers?', type:'open', answer:'10', unit:'children', solution:'90 ÷ 9 = 10.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-289', stem:'$63 is shared equally among 9 friends. How much does each person get?', type:'open', answer:'7', unit:'$', solution:'63 ÷ 9 = 7.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-290', stem:'In a class of 32 children, they sit in groups of 8. How many groups are there?', type:'open', answer:'4', unit:'groups', solution:'32 ÷ 8 = 4.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-291', stem:'A bottle holds 5 glasses of water. How many bottles are needed for 35 glasses?', type:'open', answer:'7', unit:'bottles', solution:'35 ÷ 5 = 7.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-292', stem:'96 ÷ 8 = ?', type:'open', answer:'12', solution:'96 ÷ 8 = 12.', topic:'division', diff:2, h:'Model Drawing' },
{ id:'b2-293', stem:'A number can be divided evenly by both 3 and 4. It is between 20 and 30. What is it?', type:'open', answer:'24', solution:'LCM(3,4)=12. Between 20-30: 24. ✓', topic:'division', diff:3, h:'Logical Reasoning' },
{ id:'b2-294', stem:'Divide 90 equally among 6. What is the result?', type:'open', answer:'15', solution:'90 ÷ 6 = 15.', topic:'division', diff:2, h:'Model Drawing' },
{ id:'b2-295', stem:'Each box holds 6 bottles. How many full boxes can be filled with 50 bottles? How many are left over?', type:'open', answer:'8 boxes, 2 left over', solution:'50÷6=8 remainder 2.', topic:'division', diff:2, h:'Model Drawing' },
{ id:'b2-296', stem:'How many groups of 7 can I make from 98?', type:'open', answer:'14', solution:'98 ÷ 7 = 14.', topic:'division', diff:2, h:'Model Drawing' },
{ id:'b2-297', stem:'A number divided by 5 gives 9 with no remainder. What is the number?', type:'open', answer:'45', solution:'5 × 9 = 45.', topic:'division', diff:2, h:'Work Backwards' },
{ id:'b2-298', stem:'A swimming pool is 50 metres long. Amy swims 400 metres in total. How many laps did she swim?', type:'open', answer:'8', unit:'laps', solution:'400 ÷ 50 = 8.', topic:'division', diff:2, h:'Model Drawing' },
{ id:'b2-299', stem:'How many sevens are there in 56?', type:'open', answer:'8', solution:'56 ÷ 7 = 8.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-300', stem:'24 muffins are packed in boxes of 6. Each box costs $5. How much do all the boxes cost?', type:'open', answer:'20', unit:'$', solution:'Boxes: 24÷6=4. Cost: 4×$5=$20.', topic:'division', diff:2, h:'Model Drawing' },
{ id:'b2-301', stem:'A necklace uses 8 beads per strand. There are 6 strands. How many beads are used? If 5 extra beads are left over, how many beads were there at the start?', type:'open', answer:'53', unit:'beads', solution:'8×6=48 beads used. 48+5=53 beads at start.', topic:'division', diff:2, h:'Work Backwards' },
{ id:'b2-302', stem:'36 ÷ 4 + 8 = ?', type:'open', answer:'17', solution:'36÷4=9. 9+8=17.', topic:'division', diff:2, h:'Simplify the Problem' },
{ id:'b2-303', stem:'(48 + 12) ÷ 6 = ?', type:'open', answer:'10', solution:'48+12=60. 60÷6=10.', topic:'division', diff:2, h:'Simplify the Problem' },
{ id:'b2-304', stem:'A factory makes 63 toys a day. They pack 7 toys in each box. How many boxes are filled each day?', type:'open', answer:'9', unit:'boxes', solution:'63 ÷ 7 = 9.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-305', stem:'Divide the sum of 24 and 36 by 6.', type:'open', answer:'10', solution:'24+36=60. 60÷6=10.', topic:'division', diff:2, h:'Simplify the Problem' },
{ id:'b2-306', stem:'90 children are split into groups. Each group has 10 children. How many groups are there?', type:'open', answer:'9', unit:'groups', solution:'90 ÷ 10 = 9.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-307', stem:'A jar has 84 sweets. 7 friends share them equally. How many does each friend get?', type:'open', answer:'12', unit:'sweets', solution:'84 ÷ 7 = 12.', topic:'division', diff:2, h:'Model Drawing' },
{ id:'b2-308', stem:'48 ÷ 6 × 3 = ?', type:'open', answer:'24', solution:'48÷6=8. 8×3=24.', topic:'division', diff:2, h:'Simplify the Problem' },
{ id:'b2-309', stem:'Find the quotient when 90 is divided by 9.', type:'open', answer:'10', solution:'90 ÷ 9 = 10.', topic:'division', diff:1, h:'Model Drawing' },
{ id:'b2-310', stem:'There are 56 pages in a comic book. Sam reads 8 pages a day. How many days does he need to finish the book?', type:'open', answer:'7', unit:'days', solution:'56 ÷ 8 = 7.', topic:'division', diff:1, h:'Model Drawing' },

// ── MONEY (Q311–360) ───────────────────────────────────────────────────────

{ id:'b2-311', stem:'A pen costs $3 and an eraser costs $1. How much do 3 pens and 2 erasers cost?', type:'open', answer:'11', unit:'$', solution:'3×$3=$9. 2×$1=$2. Total: $9+$2=$11.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-312', stem:'Ali has $50. He buys a toy for $23. How much does he have left?', type:'open', answer:'27', unit:'$', solution:'$50−$23=$27.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-313', stem:'A notebook costs $4. How much do 7 notebooks cost?', type:'open', answer:'28', unit:'$', solution:'7×$4=$28.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-314', stem:'Sarah has $65. She spends $28 on shoes and $14 on a bag. How much is left?', type:'open', answer:'23', unit:'$', solution:'$28+$14=$42. $65−$42=$23.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-315', stem:'Convert 350 cents to dollars and cents.', type:'open', answer:'$3.50', solution:'350 cents = 300 cents + 50 cents = $3 and 50 cents = $3.50.', topic:'money', diff:1, h:'Restate the Problem' },
{ id:'b2-316', stem:'Convert $4.75 to cents.', type:'open', answer:'475', unit:'cents', solution:'$4=400¢. 75¢. Total: 475¢.', topic:'money', diff:1, h:'Restate the Problem' },
{ id:'b2-317', stem:'A bag of rice costs $8. How much do 6 bags cost?', type:'open', answer:'48', unit:'$', solution:'6×$8=$48.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-318', stem:'Lily has $100. She buys 3 books at $15 each. How much money does she have left?', type:'open', answer:'55', unit:'$', solution:'3×$15=$45. $100−$45=$55.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-319', stem:'A sticker costs 50 cents. How much do 6 stickers cost?', type:'open', answer:'300', unit:'cents', solution:'6×50¢=300¢.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-320', stem:'Jan has $20. She buys 4 pencils at $1.50 each. How much does she have left?', type:'open', answer:'14', unit:'$', solution:'4×$1.50=$6. $20−$6=$14.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-321', stem:'A toy costs $15. Kim has $8. How much more money does she need?', type:'open', answer:'7', unit:'$', solution:'$15−$8=$7.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-322', stem:'Oranges cost $2 for 4. How much do 12 oranges cost?', type:'open', answer:'6', unit:'$', solution:'12÷4=3 sets. 3×$2=$6.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-323', stem:'A packet of biscuits costs $3. Tom buys 5 packets and gives $20. How much change does he get?', type:'open', answer:'5', unit:'$', solution:'5×$3=$15. $20−$15=$5.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-324', stem:'How many 50-cent coins make $4?', type:'open', answer:'8', unit:'coins', solution:'$4=400¢. 400÷50=8.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-325', stem:'A pen costs $6. An eraser costs $2. If you buy 4 pens and 3 erasers, how much do you spend?', type:'open', answer:'30', unit:'$', solution:'4×$6=$24. 3×$2=$6. $24+$6=$30.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-326', stem:'Amy saved $9 a week for 6 weeks. How much did she save in total?', type:'open', answer:'54', unit:'$', solution:'6×$9=$54.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-327', stem:'A meal costs $7. How much do 8 meals cost?', type:'open', answer:'56', unit:'$', solution:'8×$7=$56.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-328', stem:'Ben has 3 ten-dollar notes and 5 one-dollar coins. How much money does he have?', type:'open', answer:'35', unit:'$', solution:'3×$10=$30. 5×$1=$5. $30+$5=$35.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-329', stem:'A book costs $12 and a ruler costs $3. What is the total cost of 2 books and 4 rulers?', type:'open', answer:'36', unit:'$', solution:'2×$12=$24. 4×$3=$12. $24+$12=$36.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-330', stem:'Mia has $47. After buying a toy, she has $19 left. How much did the toy cost?', type:'open', answer:'28', unit:'$', solution:'$47−$19=$28.', topic:'money', diff:2, h:'Work Backwards' },
{ id:'b2-331', stem:'6 friends share a restaurant bill of $54 equally. How much does each person pay?', type:'open', answer:'9', unit:'$', solution:'$54÷6=$9.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-332', stem:'Ken buys 3 shirts at $9 each and 2 pairs of socks at $4 each. What is the total cost?', type:'open', answer:'35', unit:'$', solution:'3×$9=$27. 2×$4=$8. $27+$8=$35.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-333', stem:'A toy car costs twice as much as a ball. The ball costs $6. How much does the toy car cost?', type:'open', answer:'12', unit:'$', solution:'$6×2=$12.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-334', stem:'Sam wants to buy a book that costs $35. He has saved $18. How much more does he need?', type:'open', answer:'17', unit:'$', solution:'$35−$18=$17.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-335', stem:'A cinema ticket costs $9. How much do tickets for a family of 4 cost?', type:'open', answer:'36', unit:'$', solution:'4×$9=$36.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-336', stem:'Mrs Lee paid $50 for 5 equal items. What was the cost of each item?', type:'open', answer:'10', unit:'$', solution:'$50÷5=$10.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-337', stem:'A child has 7 fifty-cent coins. How much money does she have in dollars?', type:'open', answer:'3.50', unit:'$', solution:'7×50¢=350¢=$3.50.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-338', stem:'Ron has $100. He spends $37 on shoes and $25 on a shirt. How much does he have left?', type:'open', answer:'38', unit:'$', solution:'$37+$25=$62. $100−$62=$38.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-339', stem:'A snack costs $4. How many snacks can you buy with $36?', type:'open', answer:'9', unit:'snacks', solution:'$36÷$4=9.', topic:'money', diff:2, h:'Division / Model Drawing' },
{ id:'b2-340', stem:'Raju saves $6 each week. After how many weeks will he have $54?', type:'open', answer:'9', unit:'weeks', solution:'$54÷$6=9.', topic:'money', diff:2, h:'Division / Model Drawing' },
{ id:'b2-341', stem:'A pencil costs $2 and a sharpener costs $3. Tina buys 4 pencils and 2 sharpeners. How much does she spend?', type:'open', answer:'14', unit:'$', solution:'4×$2=$8. 2×$3=$6. $8+$6=$14.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-342', stem:'Kai has $50 and earns $8 more. He then spends $23. How much does he have now?', type:'open', answer:'35', unit:'$', solution:'$50+$8=$58. $58−$23=$35.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-343', stem:'A store has a $5 off sale. A hat normally costs $19. What is the sale price?', type:'open', answer:'14', unit:'$', solution:'$19−$5=$14.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-344', stem:'How many $5 notes make $45?', type:'open', answer:'9', unit:'notes', solution:'$45÷$5=9.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-345', stem:'A box of 6 chocolates costs $12. What is the cost of 1 chocolate?', type:'open', answer:'2', unit:'$', solution:'$12÷6=$2.', topic:'money', diff:1, h:'Model Drawing' },
{ id:'b2-346', stem:'Joey has $35. He wants to buy gifts costing $8 each. How many gifts can he buy? How much money will he have left?', type:'open', answer:'4 gifts, $3 left', solution:'35÷8=4 remainder 3. 4 gifts, $3 left.', topic:'money', diff:3, h:'Division / Model Drawing' },
{ id:'b2-347', stem:'Milk costs $3 per litre. Orange juice costs $5 per litre. What is the combined cost of 4 litres of milk and 3 litres of juice?', type:'open', answer:'27', unit:'$', solution:'4×$3=$12. 3×$5=$15. $12+$15=$27.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-348', stem:'Kate and Emma together have $88. Kate has $12 more than Emma. How much does Kate have?', type:'open', answer:'50', unit:'$', solution:'Let Emma=x. Kate=x+12. x+x+12=88. 2x=76. x=38. Kate=38+12=50.', topic:'money', diff:3, h:'Model Drawing' },
{ id:'b2-349', stem:'A shop offers "buy 3, get 1 free" on $4 notebooks. If Max takes 4 notebooks, how much does he pay?', type:'open', answer:'12', unit:'$', solution:'He pays for 3 and gets 1 free. 3×$4=$12.', topic:'money', diff:3, h:'Logical Reasoning' },
{ id:'b2-350', stem:'Tom earns $7 for each chore. He does 9 chores. He spends $38. How much does he have left?', type:'open', answer:'25', unit:'$', solution:'9×$7=$63. $63−$38=$25.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-351', stem:'A box of 8 juice bottles costs $24. What is the cost of 5 bottles?', type:'open', answer:'15', unit:'$', solution:'$24÷8=$3 each. 5×$3=$15.', topic:'money', diff:2, h:'Simplify the Problem' },
{ id:'b2-352', stem:'Grace buys 5 muffins at $3 each and pays with a $20 note. How much change does she get?', type:'open', answer:'5', unit:'$', solution:'5×$3=$15. $20−$15=$5.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-353', stem:'Ali spent $56 on books. Each book costs $8. How many books did he buy?', type:'open', answer:'7', unit:'books', solution:'$56÷$8=7.', topic:'money', diff:1, h:'Division / Model Drawing' },
{ id:'b2-354', stem:'Three friends share a bill of $72 equally. How much does each pay?', type:'open', answer:'24', unit:'$', solution:'$72÷3=$24.', topic:'money', diff:1, h:'Division / Model Drawing' },
{ id:'b2-355', stem:'An apple costs 80¢. Min has $4. How many apples can she buy?', type:'open', answer:'5', unit:'apples', solution:'400¢÷80¢=5.', topic:'money', diff:2, h:'Division / Model Drawing' },
{ id:'b2-356', stem:'A shop sells 4 cupcakes for $6. How much do 8 cupcakes cost?', type:'open', answer:'12', unit:'$', solution:'8÷4=2 sets. 2×$6=$12.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-357', stem:'Leo has some money. He spends $27 and has $45 left. How much did he start with?', type:'open', answer:'72', unit:'$', solution:'$45+$27=$72.', topic:'money', diff:2, h:'Work Backwards' },
{ id:'b2-358', stem:'A bookstore is selling books at 2 for $9. Mrs Tan buys 6 books. How much does she pay?', type:'open', answer:'27', unit:'$', solution:'6÷2=3 sets. 3×$9=$27.', topic:'money', diff:2, h:'Model Drawing' },
{ id:'b2-359', stem:'Mani has $20 more than Kavya. Together they have $80. How much does Kavya have?', type:'open', answer:'30', unit:'$', solution:'Let Kavya=x. Mani=x+20. x+x+20=80. 2x=60. x=30.', topic:'money', diff:3, h:'Model Drawing' },
{ id:'b2-360', stem:'A souvenir costs $9. How many can you buy with $72? How much money is left over?', type:'open', answer:'8 souvenirs, $0 left', solution:'$72÷$9=8 exactly. No money left.', topic:'money', diff:2, h:'Division / Model Drawing' },
];
