// lib/smc/questions-g1.ts
// SMC Grade 1 question bank sourced from the 2023 and 2025 official papers.
// Every question carries a step-by-step solution and heuristic tag so the
// solution reveal screen can explain Singapore-method thinking.

import type { SectionId, QuestionType } from './spec';

export interface SMCOption {
  letter: 'A' | 'B' | 'C' | 'D';
  text: string;
}

export interface SMCQuestion {
  id: string;
  year: 2023 | 2025;
  section: SectionId;
  questionNumber: number;         // position within paper (1–31 for 2025, 1–40 for 2023)
  stem: string;                   // question text (LaTeX-free, plain English)
  type: QuestionType;
  options?: SMCOption[];          // MCQ only
  correctAnswer: string;          // 'A'/'B'/'C'/'D' for MCQ, numeric string for open
  unit?: string;                  // e.g. 'pens', 'cents', '$'
  heuristic: string;              // Singapore heuristic used
  solution: string;               // plain English step-by-step
  commonMistake?: string;
  difficulty: 1 | 2 | 3;         // 1=routine, 2=medium, 3=non-routine
  topicTags: string[];
  estimatedSeconds: number;
}

// ---------------------------------------------------------------------------
// 2025 Paper — Section A (MCQ, 2 marks each, Q1–15)
// ---------------------------------------------------------------------------
const QUESTIONS_2025_A: SMCQuestion[] = [
  {
    id: '2025-A-1',
    year: 2025,
    section: 'A',
    questionNumber: 1,
    stem: '6 tens 12 ones is the same as ________.',
    type: 'mcq',
    options: [
      { letter: 'A', text: '18' },
      { letter: 'B', text: '62' },
      { letter: 'C', text: '72' },
      { letter: 'D', text: '78' },
    ],
    correctAnswer: 'C',
    heuristic: 'Restate the Problem',
    solution: '6 tens = 60. 12 ones = 12. 60 + 12 = 72.',
    commonMistake: 'Writing 612 instead of regrouping the ones.',
    difficulty: 1,
    topicTags: ['place-value', 'tens-ones'],
    estimatedSeconds: 45,
  },
  {
    id: '2025-A-2',
    year: 2025,
    section: 'A',
    questionNumber: 2,
    stem: 'Look at the number bond: 64 + ? = 100. What is the missing number?',
    type: 'mcq',
    options: [
      { letter: 'A', text: '35' },
      { letter: 'B', text: '36' },
      { letter: 'C', text: '40' },
      { letter: 'D', text: '54' },
    ],
    correctAnswer: 'B',
    heuristic: 'Work Backwards',
    solution: '100 − 64 = 36. Count up: 64 + 6 = 70, 70 + 30 = 100. So 36.',
    difficulty: 1,
    topicTags: ['addition', 'subtraction', 'number-bonds'],
    estimatedSeconds: 45,
  },
  {
    id: '2025-A-3',
    year: 2025,
    section: 'A',
    questionNumber: 3,
    stem: 'Caitlyn bought a bag for $21. She gave the cashier a $50-note. How much change did she get?',
    type: 'mcq',
    options: [
      { letter: 'A', text: '$71' },
      { letter: 'B', text: '$39' },
      { letter: 'C', text: '$29' },
      { letter: 'D', text: '$19' },
    ],
    correctAnswer: 'C',
    heuristic: 'Work Backwards',
    solution: 'Change = $50 − $21 = $29.',
    commonMistake: 'Adding instead of subtracting: $50 + $21 = $71.',
    difficulty: 1,
    topicTags: ['money', 'subtraction'],
    estimatedSeconds: 45,
  },
  {
    id: '2025-A-4',
    year: 2025,
    section: 'A',
    questionNumber: 4,
    stem: 'Which pair of numbers makes 7 tens (70)?',
    type: 'mcq',
    options: [
      { letter: 'A', text: '52 and 18' },
      { letter: 'B', text: '43 and 17' },
      { letter: 'C', text: '10 and 7' },
      { letter: 'D', text: '43 and 37' },
    ],
    correctAnswer: 'A',
    heuristic: 'Guess and Check',
    solution: '52 + 18 = 70. Check: 43+17=60 ✗, 10+7=17 ✗, 43+37=80 ✗.',
    difficulty: 1,
    topicTags: ['addition', 'place-value'],
    estimatedSeconds: 60,
  },
  {
    id: '2025-A-5',
    year: 2025,
    section: 'A',
    questionNumber: 5,
    stem: 'Violet cut a cake into 15 slices. She gave 3 slices to Joyce and 6 slices to Savannah. Then, she shared the rest equally with her 2 sisters. How many slices of cake did each sister receive?',
    type: 'mcq',
    options: [
      { letter: 'A', text: '9' },
      { letter: 'B', text: '2' },
      { letter: 'C', text: '3' },
      { letter: 'D', text: '6' },
    ],
    correctAnswer: 'C',
    heuristic: 'Model Drawing',
    solution: 'Slices given away: 3 + 6 = 9. Slices left: 15 − 9 = 6. Shared with 2 sisters: 6 ÷ 2 = 3 each.',
    commonMistake: 'Forgetting that Violet also shares (dividing by 2 instead of 3).',
    difficulty: 2,
    topicTags: ['division', 'multi-step', 'subtraction'],
    estimatedSeconds: 90,
  },
  {
    id: '2025-A-8',
    year: 2025,
    section: 'A',
    questionNumber: 8,
    stem: '15 + 8 + 17 = ? tens. What is the missing number?',
    type: 'mcq',
    options: [
      { letter: 'A', text: '40' },
      { letter: 'B', text: '23' },
      { letter: 'C', text: '25' },
      { letter: 'D', text: '4' },
    ],
    correctAnswer: 'D',
    heuristic: 'Restate the Problem',
    solution: '15 + 8 + 17 = 40. 40 = 4 tens. The missing number is 4.',
    difficulty: 1,
    topicTags: ['addition', 'place-value'],
    estimatedSeconds: 60,
  },
  {
    id: '2025-A-9',
    year: 2025,
    section: 'A',
    questionNumber: 9,
    stem: 'Melanie is thinking of a 2-digit number. The digit in the tens place is 5 more than 2. The digit in the ones place is 4 less than the digit in the tens place. What is the number?',
    type: 'mcq',
    options: [
      { letter: 'A', text: '37' },
      { letter: 'B', text: '57' },
      { letter: 'C', text: '73' },
      { letter: 'D', text: '75' },
    ],
    correctAnswer: 'C',
    heuristic: 'Logical Reasoning',
    solution: 'Tens digit = 5 + 2 = 7. Ones digit = 7 − 4 = 3. Number = 73.',
    difficulty: 2,
    topicTags: ['place-value', 'logical-reasoning'],
    estimatedSeconds: 90,
  },
  {
    id: '2025-A-10',
    year: 2025,
    section: 'A',
    questionNumber: 10,
    stem: 'Cassandra has 24 lollipops. She shares them equally with 3 friends. How many lollipops will she get?',
    type: 'mcq',
    options: [
      { letter: 'A', text: '27' },
      { letter: 'B', text: '21' },
      { letter: 'C', text: '8' },
      { letter: 'D', text: '6' },
    ],
    correctAnswer: 'D',
    heuristic: 'Model Drawing',
    solution: 'Cassandra + 3 friends = 4 people total. 24 ÷ 4 = 6 each.',
    commonMistake: 'Dividing by 3 instead of 4 (forgetting Cassandra herself): 24 ÷ 3 = 8.',
    difficulty: 2,
    topicTags: ['division', 'problem-solving'],
    estimatedSeconds: 90,
  },
  {
    id: '2025-A-15',
    year: 2025,
    section: 'A',
    questionNumber: 15,
    stem: 'Jaclyn is shorter than Wallace. Michelle is shorter than Wallace. Jaclyn is taller than Michelle. Lydia is shorter than Michelle. Who is the shortest?',
    type: 'mcq',
    options: [
      { letter: 'A', text: 'Jaclyn' },
      { letter: 'B', text: 'Michelle' },
      { letter: 'C', text: 'Wallace' },
      { letter: 'D', text: 'Lydia' },
    ],
    correctAnswer: 'D',
    heuristic: 'Logical Reasoning / Elimination',
    solution: 'Order tall→short: Wallace > Jaclyn > Michelle > Lydia. Lydia is shortest.',
    difficulty: 2,
    topicTags: ['comparison', 'logical-reasoning', 'ordering'],
    estimatedSeconds: 90,
  },
];

// ---------------------------------------------------------------------------
// 2025 Paper — Section B (open-ended, 4 marks each, Q16–25)
// ---------------------------------------------------------------------------
const QUESTIONS_2025_B: SMCQuestion[] = [
  {
    id: '2025-B-17',
    year: 2025,
    section: 'B',
    questionNumber: 17,
    stem: '24 boys and 19 girls are in the canteen. 5 boys leave the canteen but 12 more girls join in. How many children are in the canteen in the end?',
    type: 'open',
    correctAnswer: '50',
    unit: 'children',
    heuristic: 'Model Drawing',
    solution: 'Start: 24 boys + 19 girls = 43 children. Boys left: 24 − 5 = 19. Girls now: 19 + 12 = 31. Total: 19 + 31 = 50.',
    difficulty: 2,
    topicTags: ['addition', 'subtraction', 'multi-step'],
    estimatedSeconds: 120,
  },
  {
    id: '2025-B-21',
    year: 2025,
    section: 'B',
    questionNumber: 21,
    stem: 'Miss Ng has $85. She buys 4 cakes. Each cake costs $10. How much money does she have left?',
    type: 'open',
    correctAnswer: '45',
    unit: '$',
    heuristic: 'Model Drawing',
    solution: 'Cost of 4 cakes: 4 × $10 = $40. Money left: $85 − $40 = $45.',
    difficulty: 1,
    topicTags: ['money', 'multiplication', 'subtraction'],
    estimatedSeconds: 90,
  },
  {
    id: '2025-B-23',
    year: 2025,
    section: 'B',
    questionNumber: 23,
    stem: '5 circles are used to form one side of a square. How many circles are used to form all sides of the square?',
    type: 'open',
    correctAnswer: '16',
    unit: 'circles',
    heuristic: 'Draw a Diagram',
    solution: 'Each side has 5 circles but the 4 corner circles are shared between 2 sides. Total = 4 sides × 5 − 4 corners (counted twice) = 20 − 4 = 16.',
    commonMistake: 'Multiplying 5 × 4 = 20 without subtracting shared corners.',
    difficulty: 2,
    topicTags: ['geometry', 'patterns', 'problem-solving'],
    estimatedSeconds: 120,
  },
  {
    id: '2025-B-24',
    year: 2025,
    section: 'B',
    questionNumber: 24,
    stem: 'Sharon has a $2-note. She wants to exchange the note for coins of 10¢ and 50¢ only. How many ways can she exchange with her $2-note?',
    type: 'open',
    correctAnswer: '5',
    unit: 'ways',
    heuristic: 'Make a Systematic List',
    solution: '$2 = 200¢. Let x = number of 50¢ coins, y = number of 10¢ coins. 50x + 10y = 200 → 5x + y = 20. x=0:y=20 ✓, x=1:y=15 ✓, x=2:y=10 ✓, x=3:y=5 ✓, x=4:y=0 ✓. Total = 5 ways.',
    difficulty: 3,
    topicTags: ['money', 'systematic-listing', 'problem-solving'],
    estimatedSeconds: 180,
  },
];

// ---------------------------------------------------------------------------
// 2025 Paper — Section C (open-ended, 5 marks each, Q26–31)
// ---------------------------------------------------------------------------
const QUESTIONS_2025_C: SMCQuestion[] = [
  {
    id: '2025-C-26',
    year: 2025,
    section: 'C',
    questionNumber: 26,
    stem: "Uncle Wong has some fruits in his shop. He has 11 more apples than oranges. He has 1 less papaya than oranges. 8 of his fruits are either papayas or mangoes. He has 3 mangoes. How many fruits does Uncle Wong have altogether?",
    type: 'open',
    correctAnswer: '31',
    unit: 'fruits',
    heuristic: 'Model Drawing / Work Backwards',
    solution: 'Papayas + mangoes = 8. Mangoes = 3 → Papayas = 5. Papayas = Oranges − 1 → Oranges = 6. Apples = 6 + 11 = 17. Total = 17 + 6 + 5 + 3 = 31.',
    difficulty: 3,
    topicTags: ['multi-step', 'logical-reasoning', 'addition'],
    estimatedSeconds: 240,
  },
  {
    id: '2025-C-27',
    year: 2025,
    section: 'C',
    questionNumber: 27,
    stem: 'Magdelene had 70 sweets. She gave away 38 sweets and bought another 54 sweets. How many sweets did she have in the end?',
    type: 'open',
    correctAnswer: '86',
    unit: 'sweets',
    heuristic: 'Model Drawing',
    solution: '70 − 38 = 32 sweets left. 32 + 54 = 86 sweets in the end.',
    difficulty: 2,
    topicTags: ['addition', 'subtraction', 'multi-step'],
    estimatedSeconds: 120,
  },
  {
    id: '2025-C-31',
    year: 2025,
    section: 'C',
    questionNumber: 31,
    stem: 'Mr Song left his house at 8 o\'clock in the morning and reached his office at 8:35. How many minutes did he travel from home to his office?',
    type: 'open',
    correctAnswer: '35',
    unit: 'min',
    heuristic: 'Draw a Diagram (Timeline)',
    solution: 'From 8:00 to 8:35 = 35 minutes.',
    difficulty: 2,
    topicTags: ['time', 'elapsed-time'],
    estimatedSeconds: 90,
  },
];

// ---------------------------------------------------------------------------
// 2023 Paper — All 40 questions (open-ended format)
// ---------------------------------------------------------------------------
const QUESTIONS_2023: SMCQuestion[] = [
  // Section A (2 marks each)
  {
    id: '2023-A-1',
    year: 2023,
    section: 'A',
    questionNumber: 1,
    stem: 'A picture shows 9 butterflies split into 2 groups. One group has 2 butterflies. How many butterflies are in the other group?',
    type: 'open',
    correctAnswer: '7',
    unit: 'butterflies',
    heuristic: 'Model Drawing',
    solution: '9 − 2 = 7.',
    difficulty: 1,
    topicTags: ['subtraction', 'number-bonds'],
    estimatedSeconds: 30,
  },
  {
    id: '2023-A-4',
    year: 2023,
    section: 'A',
    questionNumber: 4,
    stem: 'Set A has coins worth 50¢, 20¢, 10¢, 5¢ and 5¢. Set B has coins worth 50¢, 50¢, 20¢, 10¢ and 5¢. What is the total amount of money in the set that has more money? Give your answer in cents.',
    type: 'open',
    correctAnswer: '135',
    unit: 'cents',
    heuristic: 'Simplify the Problem',
    solution: 'Set A: 50+20+10+5+5 = 90¢. Set B: 50+50+20+10+5 = 135¢. Set B has more. Answer: 135¢.',
    difficulty: 2,
    topicTags: ['money', 'addition', 'comparison'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-A-5',
    year: 2023,
    section: 'A',
    questionNumber: 5,
    stem: 'There are 4 red pens and 3 blue pens in 1 box. How many pens are there in 3 such boxes?',
    type: 'open',
    correctAnswer: '21',
    unit: 'pens',
    heuristic: 'Model Drawing',
    solution: 'Pens per box: 4 + 3 = 7. Total for 3 boxes: 7 × 3 = 21.',
    difficulty: 1,
    topicTags: ['multiplication', 'addition'],
    estimatedSeconds: 60,
  },
  {
    id: '2023-A-7',
    year: 2023,
    section: 'A',
    questionNumber: 7,
    stem: 'There are 8 groups of students in Primary 1 Joy class. Miss Ellen puts exactly 3 students in each group. How many students are there in Primary 1 Joy altogether?',
    type: 'open',
    correctAnswer: '24',
    unit: 'students',
    heuristic: 'Model Drawing',
    solution: '8 groups × 3 students = 24 students.',
    difficulty: 1,
    topicTags: ['multiplication'],
    estimatedSeconds: 45,
  },
  {
    id: '2023-A-8',
    year: 2023,
    section: 'A',
    questionNumber: 8,
    stem: 'Ron and Mike have 12 marbles altogether. Each of them has more than 4 marbles. Ron has fewer marbles than Mike. How many marbles does Mike have?',
    type: 'open',
    correctAnswer: '7',
    unit: 'marbles',
    heuristic: 'Guess and Check',
    solution: 'Each has more than 4 marbles, so each has at least 5. Total is 12. Try Ron=5, Mike=7: 5+7=12 ✓, both>4 ✓, Ron<Mike ✓. Mike has 7.',
    difficulty: 2,
    topicTags: ['logical-reasoning', 'guess-and-check', 'addition'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-A-9',
    year: 2023,
    section: 'A',
    questionNumber: 9,
    stem: 'Andy placed 2 bottles on one side of a square. How many bottles does Andy need to go round 3 squares?',
    type: 'open',
    correctAnswer: '24',
    unit: 'bottles',
    heuristic: 'Draw a Diagram',
    solution: 'Each square has 4 sides × 2 bottles = 8 bottles. 3 squares = 3 × 8 = 24 bottles.',
    difficulty: 2,
    topicTags: ['multiplication', 'geometry'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-A-12',
    year: 2023,
    section: 'A',
    questionNumber: 12,
    stem: 'Mr Chan has $50. He wants to buy a doll ($39) and 2 teddy bears ($15 each). How much more money does he need to buy the three items?',
    type: 'open',
    correctAnswer: '19',
    unit: '$',
    heuristic: 'Model Drawing',
    solution: 'Total cost: $39 + 2×$15 = $39 + $30 = $69. Extra needed: $69 − $50 = $19.',
    difficulty: 2,
    topicTags: ['money', 'multiplication', 'subtraction', 'multi-step'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-A-15',
    year: 2023,
    section: 'A',
    questionNumber: 15,
    stem: 'Karen has $26. Karen and Leon have $99 altogether. How much more money does Karen have than Leon?',
    type: 'open',
    correctAnswer: '47',
    unit: '$',
    heuristic: 'Model Drawing / Work Backwards',
    solution: 'Leon = $99 − $26 = $73. Leon has more than Karen. Karen needs: $73 − $26 = $47 more to equal Leon. But question asks "how much more does Karen have" — since Leon has more, Karen actually has $47 LESS. Answer: $47 less (or the question may be phrased as Leon having $47 more).',
    commonMistake: 'Answering $47 without noting Karen has less than Leon.',
    difficulty: 2,
    topicTags: ['subtraction', 'comparison', 'money'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-A-16',
    year: 2023,
    section: 'A',
    questionNumber: 16,
    stem: 'Cindy bakes cookies from 2.45 p.m. to 3.15 p.m. How many minutes does she take to bake the cookies?',
    type: 'open',
    correctAnswer: '30',
    unit: 'min',
    heuristic: 'Draw a Diagram (Timeline)',
    solution: 'From 2:45 to 3:00 = 15 min. From 3:00 to 3:15 = 15 min. Total = 30 min.',
    difficulty: 1,
    topicTags: ['time', 'elapsed-time'],
    estimatedSeconds: 60,
  },
  {
    id: '2023-A-17',
    year: 2023,
    section: 'A',
    questionNumber: 17,
    stem: "Samuel folded 19 paper aeroplanes. His brother folded 17 more paper aeroplanes than him. How many paper aeroplanes did his brother fold?",
    type: 'open',
    correctAnswer: '36',
    unit: 'paper aeroplanes',
    heuristic: 'Model Drawing',
    solution: 'Brother = 19 + 17 = 36.',
    difficulty: 1,
    topicTags: ['addition', 'comparison'],
    estimatedSeconds: 45,
  },
  {
    id: '2023-A-18',
    year: 2023,
    section: 'A',
    questionNumber: 18,
    stem: "Linda has $70. Mandy has 5 five-dollar notes. How much money do they have altogether?",
    type: 'open',
    correctAnswer: '95',
    unit: '$',
    heuristic: 'Model Drawing',
    solution: 'Mandy: 5 × $5 = $25. Total: $70 + $25 = $95.',
    difficulty: 1,
    topicTags: ['money', 'multiplication', 'addition'],
    estimatedSeconds: 60,
  },
  {
    id: '2023-A-19',
    year: 2023,
    section: 'A',
    questionNumber: 19,
    stem: 'Study the pattern: Row 1: 1, 4, 7, 10. Row 2: 22, 19, 16, 13. Row 3: 25, ?, ... What is the missing number?',
    type: 'open',
    correctAnswer: '28',
    unit: '',
    heuristic: 'Look for Patterns',
    solution: 'Each row increases by 3 going right. Row 3 starts at 25, so 25 + 3 = 28.',
    difficulty: 2,
    topicTags: ['patterns', 'number-sequences'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-A-20',
    year: 2023,
    section: 'A',
    questionNumber: 20,
    stem: 'Tammy has to choose one activity in each of Term 3 and Term 4. Term 3 has 3 activities (Drawing, Gymnasium, Junior Chef). Term 4 has 2 activities (Sculpture, Pottery). How many sets of choices can Tammy choose?',
    type: 'open',
    correctAnswer: '6',
    unit: 'choices',
    heuristic: 'Make a Systematic List',
    solution: '3 Term 3 activities × 2 Term 4 activities = 6 combinations.',
    difficulty: 2,
    topicTags: ['combinations', 'systematic-listing'],
    estimatedSeconds: 120,
  },
  // Section B (3 marks each, 2023 format)
  {
    id: '2023-B-21',
    year: 2023,
    section: 'B',
    questionNumber: 21,
    stem: 'For every 10 apples bought, 2 free apples are given. Mrs Lee received 6 free apples. How many apples did she have altogether?',
    type: 'open',
    correctAnswer: '36',
    unit: 'apples',
    heuristic: 'Look for Patterns',
    solution: '6 free apples ÷ 2 = 3 boxes of 10. Bought: 3 × 10 = 30. Total: 30 + 6 = 36.',
    difficulty: 2,
    topicTags: ['multiplication', 'division', 'problem-solving'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-B-22',
    year: 2023,
    section: 'B',
    questionNumber: 22,
    stem: 'Joseph used a calculator to find 45 + 36 + 7. The answer shown was 48. One number button was not working. Which number button was not working?',
    type: 'open',
    correctAnswer: '4',
    unit: '',
    heuristic: 'Guess and Check',
    solution: 'Correct: 45+36+7=88. If "4" does not work: 05+06+7 = 5+6+7+... Wait: 45 becomes 05=5, so 5+36+7=48. Yes! Button "4" was broken.',
    difficulty: 3,
    topicTags: ['logical-reasoning', 'addition', 'problem-solving'],
    estimatedSeconds: 180,
  },
  {
    id: '2023-B-24',
    year: 2023,
    section: 'B',
    questionNumber: 24,
    stem: 'Linette had some toys. She gave away 18 toys and threw away 15 of them. She had 28 toys left. How many toys did Linette have at first?',
    type: 'open',
    correctAnswer: '61',
    unit: 'toys',
    heuristic: 'Work Backwards',
    solution: 'Work backwards: 28 + 15 + 18 = 61 toys at first.',
    difficulty: 2,
    topicTags: ['addition', 'work-backwards', 'multi-step'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-B-25',
    year: 2023,
    section: 'B',
    questionNumber: 25,
    stem: 'Mdm Fatimah bought 3 bags of cookies. There were 8 cookies in each bag. She repacked all the cookies into smaller packs of 4 each. How many packs of 4 cookies did she have?',
    type: 'open',
    correctAnswer: '6',
    unit: 'packs',
    heuristic: 'Model Drawing',
    solution: 'Total cookies: 3 × 8 = 24. Packs of 4: 24 ÷ 4 = 6.',
    difficulty: 2,
    topicTags: ['multiplication', 'division', 'multi-step'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-B-26',
    year: 2023,
    section: 'B',
    questionNumber: 26,
    stem: 'Siti wants to exchange a $50 note for $5 and $10 notes. She will get four $5 notes and some $10 notes. How many $10 notes will Siti get?',
    type: 'open',
    correctAnswer: '3',
    unit: '$10 notes',
    heuristic: 'Work Backwards',
    solution: '4 × $5 = $20. Remaining: $50 − $20 = $30. $30 ÷ $10 = 3 notes.',
    difficulty: 2,
    topicTags: ['money', 'division', 'subtraction'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-B-27',
    year: 2023,
    section: 'B',
    questionNumber: 27,
    stem: 'Raja uses 2 slices of bread and 1 slice of ham per sandwich. What is the total number of slices of bread and ham used to make 4 sandwiches?',
    type: 'open',
    correctAnswer: '12',
    unit: 'slices',
    heuristic: 'Look for Patterns',
    solution: 'Bread for 4 sandwiches: 4 × 2 = 8. Ham for 4 sandwiches: 4 × 1 = 4. Total: 8 + 4 = 12.',
    difficulty: 1,
    topicTags: ['multiplication', 'addition', 'patterns'],
    estimatedSeconds: 90,
  },
  {
    id: '2023-B-29',
    year: 2023,
    section: 'B',
    questionNumber: 29,
    stem: 'Kenneth is thinking of a 2-digit number that is greater than 31 but smaller than 40. When the two digits are added together, the answer is 9. What number is Kenneth thinking of?',
    type: 'open',
    correctAnswer: '36',
    unit: '',
    heuristic: 'Guess and Check',
    solution: 'Numbers 32–39: check digit sums. 3+6=9 ✓ → 36. (Others: 3+2=5, 3+3=6, 3+4=7, 3+5=8, 3+7=10, 3+8=11, 3+9=12.)',
    difficulty: 2,
    topicTags: ['logical-reasoning', 'place-value', 'guess-and-check'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-B-30',
    year: 2023,
    section: 'B',
    questionNumber: 30,
    stem: 'There are 6 boys and girls altogether. Each boy gets 3 sweets. Each girl gets 2 sweets. All the children share a total of 16 sweets. How many boys are there?',
    type: 'open',
    correctAnswer: '4',
    unit: 'boys',
    heuristic: 'Guess and Check / Assumption Method',
    solution: 'Assume all 6 are girls: 6 × 2 = 12 sweets, but we have 16 — that is 4 extra. Each boy gives 3−2=1 extra sweet. So number of boys = 4.',
    commonMistake: 'Setting up the equation wrong.',
    difficulty: 3,
    topicTags: ['assumption-method', 'logical-reasoning', 'multi-step'],
    estimatedSeconds: 180,
  },
  {
    id: '2023-B-31',
    year: 2023,
    section: 'B',
    questionNumber: 31,
    stem: 'Mr and Mrs Lee had lunch. Mr Lee ordered the most expensive pasta ($9). Mrs Lee ordered the cheapest pizza ($10). Both ordered a non-juice drink ($3 each). The restaurant charged $2 for service. How much did they pay in total?',
    type: 'open',
    correctAnswer: '27',
    unit: '$',
    heuristic: 'Model Drawing',
    solution: '$9 + $10 + $3 + $3 + $2 = $27.',
    difficulty: 2,
    topicTags: ['money', 'addition', 'multi-step', 'reading-data'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-B-32',
    year: 2023,
    section: 'B',
    questionNumber: 32,
    stem: 'Brandon had 19 rubber bands. He had 7 fewer rubber bands than James. How many rubber bands did they have altogether?',
    type: 'open',
    correctAnswer: '45',
    unit: 'rubber bands',
    heuristic: 'Model Drawing',
    solution: 'James = 19 + 7 = 26. Total = 19 + 26 = 45.',
    difficulty: 1,
    topicTags: ['addition', 'comparison'],
    estimatedSeconds: 60,
  },
  {
    id: '2023-B-33',
    year: 2023,
    section: 'B',
    questionNumber: 33,
    stem: '4 leaves = 20. 3 ice creams = 12. What is 1 leaf + 2 ice creams?',
    type: 'open',
    correctAnswer: '13',
    unit: '',
    heuristic: 'Simplify the Problem',
    solution: '1 leaf = 20 ÷ 4 = 5. 1 ice cream = 12 ÷ 3 = 4. 5 + 4 + 4 = 13.',
    difficulty: 2,
    topicTags: ['division', 'addition', 'algebra-thinking'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-B-34',
    year: 2023,
    section: 'B',
    questionNumber: 34,
    stem: "Johnny has a book with 40 pages. How many times will the digit '2' appear at least once on all the pages?",
    type: 'open',
    correctAnswer: '13',
    unit: 'pages',
    heuristic: 'Make a Systematic List',
    solution: "Pages with a '2': 2, 12, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 32. Count: 13 pages.",
    difficulty: 3,
    topicTags: ['systematic-listing', 'digits', 'counting'],
    estimatedSeconds: 180,
  },
  {
    id: '2023-B-35',
    year: 2023,
    section: 'B',
    questionNumber: 35,
    stem: 'Emma baked 12 more pies than Danielle. Florence baked 4 fewer pies than Danielle. Danielle baked 12 pies. How many pies did the 3 girls bake altogether?',
    type: 'open',
    correctAnswer: '44',
    unit: 'pies',
    heuristic: 'Model Drawing',
    solution: 'Emma = 12 + 12 = 24. Danielle = 12. Florence = 12 − 4 = 8. Total = 24 + 12 + 8 = 44.',
    difficulty: 2,
    topicTags: ['addition', 'subtraction', 'comparison', 'multi-step'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-B-36',
    year: 2023,
    section: 'B',
    questionNumber: 36,
    stem: 'Daniel bought 12 lollipops. He bought twice as many as Adrian. Both shared their lollipops equally with John. How many lollipops did John receive?',
    type: 'open',
    correctAnswer: '6',
    unit: 'lollipops',
    heuristic: 'Model Drawing',
    solution: 'Daniel = 12. Adrian = 12 ÷ 2 = 6. Total = 12 + 6 = 18. Shared equally by Daniel, Adrian and John: 18 ÷ 3 = 6.',
    difficulty: 3,
    topicTags: ['division', 'multiplication', 'multi-step'],
    estimatedSeconds: 180,
  },
  {
    id: '2023-B-37',
    year: 2023,
    section: 'B',
    questionNumber: 37,
    stem: '3 candles + 1 cupcake = 60. 1 burger + 1 cupcake = 65. 1 burger = 20. What is the value of 1 candle?',
    type: 'open',
    correctAnswer: '5',
    unit: '',
    heuristic: 'Simplify the Problem / Logical Reasoning',
    solution: 'Burger = 20. Cupcake = 65 − 20 = 45. 3 candles = 60 − 45 = 15. 1 candle = 15 ÷ 3 = 5.',
    difficulty: 3,
    topicTags: ['algebra-thinking', 'subtraction', 'division'],
    estimatedSeconds: 180,
  },
  {
    id: '2023-B-38',
    year: 2023,
    section: 'B',
    questionNumber: 38,
    stem: 'Leonard baked more than 20 but less than 30 pies. He could put them on trays of 3 or on trays of 4. How many pies did Leonard bake?',
    type: 'open',
    correctAnswer: '24',
    unit: 'pies',
    heuristic: 'Guess and Check / Look for Patterns',
    solution: 'Need a number between 21–29 divisible by both 3 and 4. LCM(3,4)=12. Only 24 fits (20<24<30). Answer: 24.',
    difficulty: 3,
    topicTags: ['division', 'logical-reasoning', 'multiples'],
    estimatedSeconds: 180,
  },
  {
    id: '2023-B-39',
    year: 2023,
    section: 'B',
    questionNumber: 39,
    stem: "Annie was 15 years old 3 years ago. Margaret is 4 years older than Annie. How old will Margaret be 7 years later?",
    type: 'open',
    correctAnswer: '29',
    unit: 'years old',
    heuristic: 'Work Backwards',
    solution: "Annie now = 15 + 3 = 18. Margaret now = 18 + 4 = 22. Margaret in 7 years = 22 + 7 = 29.",
    difficulty: 2,
    topicTags: ['age-problems', 'addition', 'multi-step'],
    estimatedSeconds: 120,
  },
  {
    id: '2023-B-40',
    year: 2023,
    section: 'B',
    questionNumber: 40,
    stem: 'Watermelon = $15, Grapes = $22, Mango = $7, Strawberries = $16. Mr Tan would need $4 more to buy a mango and grapes. In the end, he bought a watermelon and a mango. How much money did he have left?',
    type: 'open',
    correctAnswer: '3',
    unit: '$',
    heuristic: 'Work Backwards',
    solution: 'Mr Tan has: $7+$22−$4 = $25. Spent on watermelon+mango: $15+$7 = $22. Left: $25−$22 = $3.',
    difficulty: 3,
    topicTags: ['money', 'multi-step', 'work-backwards'],
    estimatedSeconds: 180,
  },
];

// ---------------------------------------------------------------------------
// Combined export
// ---------------------------------------------------------------------------
export const ALL_QUESTIONS_G1: SMCQuestion[] = [
  ...QUESTIONS_2025_A,
  ...QUESTIONS_2025_B,
  ...QUESTIONS_2025_C,
  ...QUESTIONS_2023,
];

export const QUESTIONS_BY_YEAR = {
  2025: [...QUESTIONS_2025_A, ...QUESTIONS_2025_B, ...QUESTIONS_2025_C],
  2023: QUESTIONS_2023,
};

export function getQuestionsBySection(year: 2023 | 2025, section: SectionId) {
  return QUESTIONS_BY_YEAR[year].filter((q) => q.section === section);
}

export function getQuestionsByTopic(topic: string) {
  return ALL_QUESTIONS_G1.filter((q) => q.topicTags.includes(topic));
}

export function getQuestionsByDifficulty(d: 1 | 2 | 3) {
  return ALL_QUESTIONS_G1.filter((q) => q.difficulty === d);
}
