-- 0003_seed_flashcards.sql
-- One-time seed: 42 hand-authored starter flashcards across 5 decks.
-- Run ONCE in the Supabase SQL editor (re-running creates duplicates).

insert into flashcards (deck, mode, skill_level, concept, detail, emoji, theme_tags, source) values
  ('multiplication', 'advanced', 1, '2 × 3', '6', '✖️', '{}', 'authored'),
  ('multiplication', 'advanced', 1, '3 × 4', '12', '✖️', '{}', 'authored'),
  ('multiplication', 'advanced', 1, '4 × 5', '20', '✖️', '{}', 'authored'),
  ('multiplication', 'advanced', 2, '6 × 7', '42', '✖️', '{}', 'authored'),
  ('multiplication', 'advanced', 2, '7 × 8', '56', '✖️', '{}', 'authored'),
  ('multiplication', 'advanced', 2, '8 × 9', '72', '✖️', '{}', 'authored'),
  ('multiplication', 'advanced', 3, '9 × 9', '81', '✖️', '{}', 'authored'),
  ('multiplication', 'advanced', 3, '11 × 6', '66', '✖️', '{}', 'authored'),
  ('geography', 'advanced', 1, 'Capital of India', 'New Delhi', '🇮🇳', '{}', 'authored'),
  ('geography', 'advanced', 1, 'Capital of France', 'Paris', '🗼', '{}', 'authored'),
  ('geography', 'advanced', 1, 'Capital of the USA', 'Washington, D.C.', '🦅', '{}', 'authored'),
  ('geography', 'advanced', 2, 'Capital of Japan', 'Tokyo', '🗾', '{}', 'authored'),
  ('geography', 'advanced', 2, 'Largest ocean', 'The Pacific Ocean', '🌊', '{}', 'authored'),
  ('geography', 'advanced', 2, 'Longest river in the world', 'The Nile', '🐊', '{}', 'authored'),
  ('geography', 'advanced', 2, 'Largest desert', 'The Sahara', '🏜️', '{}', 'authored'),
  ('geography', 'advanced', 3, 'Tallest mountain in the world', 'Mount Everest', '🏔️', '{}', 'authored'),
  ('geography', 'advanced', 3, 'Largest country by area', 'Russia', '🗺️', '{}', 'authored'),
  ('science', 'advanced', 1, 'Planet closest to the Sun', 'Mercury', '☀️', '{}', 'authored'),
  ('science', 'advanced', 1, 'Gas we breathe in to live', 'Oxygen', '🫁', '{}', 'authored'),
  ('science', 'advanced', 1, 'Color of plant leaves', 'Green', '🍃', '{}', 'authored'),
  ('science', 'advanced', 2, 'Water freezes at', '0°C (32°F)', '❄️', '{}', 'authored'),
  ('science', 'advanced', 2, 'Center of an atom', 'The nucleus', '⚛️', '{}', 'authored'),
  ('science', 'advanced', 2, 'Gas plants release that we breathe', 'Oxygen', '🌳', '{}', 'authored'),
  ('science', 'advanced', 3, 'Number of bones in the adult human body', '206', '🦴', '{}', 'authored'),
  ('science', 'advanced', 3, 'Force that pulls objects to the ground', 'Gravity', '🍎', '{}', 'authored'),
  ('animals', 'advanced', 1, 'Largest land animal', 'The African Elephant', '🐘', '{}', 'authored'),
  ('animals', 'advanced', 1, 'Fastest land animal', 'The Cheetah', '🐆', '{}', 'authored'),
  ('animals', 'advanced', 1, 'Animal known as the king of the jungle', 'The Lion', '🦁', '{}', 'authored'),
  ('animals', 'advanced', 2, 'Largest animal in the world', 'The Blue Whale', '🐋', '{}', 'authored'),
  ('animals', 'advanced', 2, 'Animal that can change its skin color', 'The Chameleon', '🦎', '{}', 'authored'),
  ('animals', 'advanced', 2, 'Tallest animal in the world', 'The Giraffe', '🦒', '{}', 'authored'),
  ('animals', 'advanced', 3, 'Insect that makes honey', 'The Bee', '🐝', '{}', 'authored'),
  ('space', 'advanced', 1, 'Our home planet', 'Earth', '🌍', '{}', 'authored'),
  ('space', 'advanced', 1, 'The star at the center of our solar system', 'The Sun', '☀️', '{}', 'authored'),
  ('space', 'advanced', 1, 'Object that orbits Earth at night', 'The Moon', '🌙', '{}', 'authored'),
  ('space', 'advanced', 2, 'Red planet in our solar system', 'Mars', '🔴', '{}', 'authored'),
  ('space', 'advanced', 2, 'Largest planet in our solar system', 'Jupiter', '🪐', '{}', 'authored'),
  ('space', 'advanced', 2, 'Planet known for its rings', 'Saturn', '🪐', '{}', 'authored'),
  ('space', 'advanced', 3, 'Galaxy that contains our solar system', 'The Milky Way', '🌌', '{}', 'authored'),
  ('space', 'advanced', 3, 'First person to walk on the Moon', 'Neil Armstrong', '👨‍🚀', '{}', 'authored'),
  ('vocabulary', 'advanced', 1, 'Opposite of "hot"', 'Cold', '🔥', '{}', 'authored'),
  ('vocabulary', 'advanced', 1, 'Opposite of "big"', 'Small', '📏', '{}', 'authored'),
  ('vocabulary', 'advanced', 2, 'A word that means "happy"', 'Joyful (or glad, cheerful)', '😊', '{}', 'authored');
